name: gomyang-cicd

on: [push]

jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      - name: Install Dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Run ESlint
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: lint
        if: ${{ always() }}

      - name: Run Tests
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: ci:test
        if: ${{ always() }}

      - name: Bundle and Output
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
        if: ${{ always() }}
